#pragma once
#include "types.h"

static constexpr PROTOCOLID MAXPROTOCOLID = 4;

enum PROTOCOL_TYPE
{
    PROTOCOL_TYPE_EXAMPLEPROTOCOL = 1,
    PROTOCOL_TYPE_EMPTYPROTOCOL = 2,
    PROTOCOL_TYPE_EMPTYPROTOCOL2 = 3,
    PROTOCOL_TYPE_REMOTELOG = 4,
};

