#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)
buildpath=$rootpath/build
deps_dir=$buildpath/deps

cd $buildpath

cmake .. --graphviz=deps.dot

dot -Tpng deps.dot -o deps.png

if [ ! -d $deps_dir ]; then
    mkdir $deps_dir
    echo $deps_dir
fi

# 只保留deps.png
mv deps* $deps_dir

mv $deps_dir/deps.png .

rm -rf $deps_dir