#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)
config_path="${rootpath}/config"

echo ${rootpath}

mkdir -e ${rootpath}/bin

PROJECT_PATH="${rootpath}/tools:${rootpath}/build_tool"
PROJECT_LD_LIBRARY_PATH="${rootpath}/debug/libs"

# 生成配置文件
cat > ~/.cassobee_config <<EOF
export PATH=${PATH}:${PROJECT_PATH}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PROJECT_LD_LIBRARY_PATH}

alias ca="cd ${rootpath}"
alias tt="cd ${rootpath}/tools"
alias cfg="cd ${rootpath}/config"
alias ss="cd ${rootpath}/source"
alias uu="cd ${rootpath}/source/bee/"
alias dd="cd ${rootpath}/debug"
alias bb="cd ${rootpath}/build"
alias pp="cd ${rootpath}/progen"
alias trace="cd ${rootpath}/debug/logdir"
alias third="cd ${rootpath}/thirdparty"

source ${rootpath}/tools/completions
complete -F process_name_completions rs
complete -F process_name_completions ks
complete -F process_name_completions mk
EOF

echo source ${rootpath}/tools/completions   	 >> ~/.cassobee_config
echo complete -F process_name_completions rs     >> ~/.cassobee_config
echo complete -F process_name_completions ks     >> ~/.cassobee_config
echo complete -F process_name_completions mk     >> ~/.cassobee_config

sh ./build_tool/setup_pretty_printer.sh

if ! grep -Fxq "source ~/.cassobee_config" ~/.bash_profile; then
    echo 'source ~/.cassobee_config' >> ~/.bash_profile
fi

source ~/.bash_profile

# 创建telegraf的30天数据保留策略
influx -execute "CREATE RETENTION POLICY \"7d\" ON \"telegraf\" DURATION 30d REPLICATION 1 DEFAULT"