#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)

echo ${rootpath}

mkdir ${rootpath}/bin

echo export PATH=$PATH:${rootpath}/tools          > ~/.cassobee_config
echo export PATH=$PATH:${rootpath}/build_tool	  > ~/.cassobee_config
echo ''                                          >> ~/.cassobee_config
echo alias ca=\"cd ${rootpath}\"                 >> ~/.cassobee_config
echo alias tt=\"cd ${rootpath}/tools\"           >> ~/.cassobee_config
echo alias ss=\"cd ${rootpath}/source\"          >> ~/.cassobee_config
echo alias uu=\"cd ${rootpath}/common\"          >> ~/.cassobee_config
echo alias dd=\"cd ${rootpath}/debug\"           >> ~/.cassobee_config
echo alias bb=\"cd ${rootpath}/build\"           >> ~/.cassobee_config
echo alias pp=\"cd ${rootpath}/progen\"          >> ~/.cassobee_config
echo alias trace=\"cd ${rootpath}/debug/logdir\" >> ~/.cassobee_config
echo alias third=\"cd ${rootpath}/thirdparty\"   >> ~/.cassobee_config

sh ./build_tool/setup_pretty_printer.sh

if ! grep -Fxq "source ~/.cassobee_config" ~/.bash_profile; then
    echo 'source ~/.cassobee_config' >> ~/.bash_profile
fi

source ~/.bash_profile
