#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)
procpath=$rootpath/debug
binpath=$rootpath/bin

if [ -z "$1" ]; then
    echo "Usage: ks <process_name>"
    echo "Available process names:"
    ls -1 $binpath | grep -E '^(run_)' | awk '{
        name = substr($0, 5, length($0) - 7)
        printf "\t%s\n", name
    }'
    exit 1
fi

process_name=$1

pgrep -af $procpath/$process_name | grep -v pgrep | grep -v gdb | awk '{print $1}' | xargs -I {} kill -SIGUSR1 {}

echo "wait $process_name exit..."

waiting_counter=0
while true; do
    running=$(pgrep -af $procpath/$process_name | grep -v pgrep | grep -v gdb)

    if [ -z "$running" ]; then
        echo "$process_name have exited."
        break
    fi

    waiting_counter=$((waiting_counter+1))
    echo retry counter:$waiting_counter
    if [ $waiting_counter -gt 10 ]; then
        echo "waiting for processes to exit timeout."
        break
    fi

    sleep 1
done
