#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)

outputfile=$rootpath/debug/cassobee.log

cd $rootpath/build && cmake .. && make -j8

echo use $outputfile as output file.

echo nohup $rootpath/debug/cassobee '>>' $outputfile '2>&1 &' > $rootpath/bin/start.sh

chmod 777 $rootpath/bin/start.sh
