#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)

if [ ! -d $rootpath/build ]; then
    mkdir $rootpath/build
    echo $rootpath/build
fi

cd $rootpath/build

cmake ..

if [ -z $1 ]; then
    make -j8
else
	make $1 -j8
fi
