#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)

xml_directory=$rootpath/progen
protocol_root_directory=$rootpath/source/protocol

$rootpath/tools/progen.py --xml $xml_directory --out $protocol_root_directory --force