#!/bin/bash

rootpath=$(cd $(dirname $0) && cd ..; pwd)

ks

rm -f $rootpath/debug/cassobee.log

echo 'wait process exit...'

sleep 5

echo 'start process...'

cd $rootpath/bin
./run_cassobee.sh
./run_client.sh